# Generated by Django 5.1.7 on 2025-03-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review1', '0003_moviemodels_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
