# Generated by Django 5.1.4 on 2025-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review1', '0005_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
